version: "3"
services:
  web:
    image: do-not-disturb:latest
    build: .
    depends_on:
      - redis
    ports: 
      - "5000:5000"
    command: ["python3", "-m", "app"]
    volumes:
      - "./:/app/"  # enable hot reload
  redis:
    image: redis:latest
    ports:
      - 6379:6379
