version: "3"
services:
  web:
    image: do-not-disturb:latest
    build:
      context: .
    ports: 
      - "5000:5000"
    command: ["python3", "-m", "app"]
  # redis:
  #   image: redis:latest
  #   depends_on:
  #     - web
  #   ports:
  #     - 6379:6379
