version: "3"
services:
  flask:
    image: do-not-disturb:latest
    build: .
    depends_on:
      - redis
    ports: 
      - "8000:80"
    volumes:
      - "./:/var/www/html/"  # enable hot reload
  redis:
    image: redis:latest
    ports:
      - 6379:6379
